# -*- coding: utf-8 -*-
"""Copy of Skin Disease

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EVQsNpBP-mnTcRGqBASyKp-ZqYA9JiR
"""

import kagglehub
pacificrm_skindiseasedataset_path = kagglehub.dataset_download('pacificrm/skindiseasedataset')

print('Data source import complete.')

import numpy as np
import pandas as pd


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

# Set image dimensions
img_size = (224, 224)
batch_size = 32

from tensorflow.keras.applications.efficientnet import preprocess_input

datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)

# Assuming pacificrm_skindiseasedataset_path is defined in a previous cell
# Example: pacificrm_skindiseasedataset_path = '/root/.cache/kagglehub/datasets/pacificrm/skindiseasedataset/versions/6'
dataset_base_path = pacificrm_skindiseasedataset_path

train_dir = os.path.join(dataset_base_path, 'SkinDisease', 'SkinDisease', 'train')
val_dir = os.path.join(dataset_base_path, 'SkinDisease', 'SkinDisease', 'train') # Assuming validation data is also in the train folder as per original code

train_generator = datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    val_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications import EfficientNetB3

base_model = EfficientNetB3(input_shape=(224, 224, 3), include_top=False, weights='imagenet')

from tensorflow.keras.layers import Dropout

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
output = Dense(22, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)



model = Model(inputs=base_model.input, outputs=output)

for layer in base_model.layers[-30:]:  # Fine-tune last 30 layers
    layer.trainable = True


model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

history = model.fit(
    train_generator,
    epochs=10,
    validation_data=val_generator
)

import matplotlib.pyplot as plt

# Accuracy
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy', marker='o')
plt.plot(history.history['val_accuracy'], label='Val Accuracy', marker='o')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss', marker='o')
plt.plot(history.history['val_loss'], label='Val Loss', marker='o')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

